name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-2025
    steps:
    
      - name: Download Parts
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dex | Out-Null

          for ($i = 1; $i -le 4; $i++) {
              $dex = "{0:D2}" -f $i
              $url = "https://raw.githubusercontent.com/raiyan088/Emulator/refs/heads/main/dex/dex$dex.bin"
              $out = "dex/dex$dex.bin"

              Write-Host "Downloading $url"
              Invoke-WebRequest $url -OutFile $out
          }
            
      - name: Show Dex Files
        run: Get-ChildItem . -Recurse
